# Generated by Django 3.2.7 on 2021-10-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210116_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='aviable',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='aviable',
            new_name='available',
        ),
    ]
