# Generated by Django 3.2.7 on 2021-10-05 19:38

from django.db import migrations, models

import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20211004_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=16, validators=[shop.models.number_greater_than_zero]),
        ),
    ]
